services:
    exsyst_api.routing.loader.api_class:
        class: EXSyst\Bundle\ApiBundle\Routing\Loader\ApiClassLoader
        arguments: [ @annotation_reader ]
        tags:
            - { name: routing.loader }
